x-django-base: &django-base
  build: blucab
  volumes:
    - ./app_db:/app/db
    - ./app_covers:/app/media/cover
    - ./app_import:/app/import
    - /etc/localtime:/etc/localtime:ro
  env_file:
    - ./.env.dev
  environment:
    - DEBUG=False
    - DJANGO_EMAIL_ENABLE_WHILE_DEBUG=False
    - SECRET_KEY="django-insecure-3@vfzox&c=0vq#=&ahgc3uyq7sv_y%391)r=3gl(h0(s0b8=t$"
    - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
    - DJANGO_CELERY_BROKER_URL=redis://:insecure-password@blucab-redis:6379/0
    - DJANGO_DB_ENGINE=postgresql
    - DJANGO_DB_NAME=blucab
    - DJANGO_DB_USER=blucab_db_user
    - DJANGO_DB_PASSWORD=insecure-blucab_user_password
    - DJANGO_DB_HOST=blucab-db
    - DJANGO_DB_PORT=5432

    # Superuser settings only for the first run and initial database initialization, then delete these entries or comment them out!
    # Select your own unique password!
    #- DJANGO_SUPERUSER_USERNAME=admin
    #- DJANGO_SUPERUSER_PASSWORD=hululu
    #- DJANGO_SUPERUSER_EMAIL=example@example.com


services:
  blucab-app:
    <<: *django-base
    container_name: blucab-app
    ports:
      - '8000:8000'
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      blucab-redis:
        condition: service_healthy
      blucab-db:
        condition: service_healthy

  blucab-db:
    image: postgres:18
    container_name: blucab-db
    # user-id from "id -u"
    user: "1000:1000"
    environment:
      - POSTGRES_DB=blucab
      - POSTGRES_USER=blucab_db_user
      - POSTGRES_PASSWORD=insecure-blucab_user_password
    volumes:
      - ./db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blucab_db_user -d blucab || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  blucab-redis:
    image: redis:alpine
    container_name: blucab-redis
    command: redis-server --requirepass "insecure-password"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "insecure-password", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  blucab-celery-worker:
    <<: *django-base
    container_name: blucab-celery-worker
    command: celery -A blucab worker -l info
    depends_on:
      blucab-redis:
        condition: service_healthy
      blucab-db:
        condition: service_healthy
      blucab-app:
        condition: service_healthy

  blucab-celery-beat:
    <<: *django-base
    container_name: blucab-celery-beat
    command: celery -A blucab beat -l info
    depends_on:
      blucab-redis:
        condition: service_healthy
      blucab-db:
        condition: service_healthy
      blucab-app:
        condition: service_healthy
