# Generated by Django 5.0.4 on 2024-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_todolist_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ean", models.CharField(max_length=16)),
                ("asin", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=128)),
                ("title_clean", models.CharField(max_length=128)),
                ("format", models.CharField(max_length=16)),
                ("release", models.CharField(max_length=4)),
                ("runtime", models.CharField(max_length=5)),
                ("fsk", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=10000)),
                ("actor", models.CharField(max_length=500)),
                ("regisseur", models.CharField(max_length=100)),
                ("studio", models.CharField(max_length=100)),
            ],
        ),
    ]
