# Generated by Django 5.0.4 on 2024-04-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_movies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Movies",
            new_name="Movie",
        ),
    ]
