# Generated by Django 5.0.4 on 2024-04-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_movies_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="actor",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
