# Generated by Django 5.0.4 on 2024-04-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_movie_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="content",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="movie",
            name="fsk",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="movie",
            name="regisseur",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="movie",
            name="release",
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name="movie",
            name="studio",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
