# Generated by Django 5.0.4 on 2024-04-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_movieuserlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
