# Generated by Django 5.0.4 on 2024-04-27 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_movieuserlist_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="movie",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="main.movie"
            ),
        ),
        migrations.AlterField(
            model_name="movieuserlist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movieuserlist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
