# Generated by Django 5.0.4 on 2024-04-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_movieuserlist_movie_alter_movieuserlist_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="activated",
            field=models.BooleanField(default=True),
        ),
    ]
