# Generated by Django 5.0.4 on 2024-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_movieuserlist_activated"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="disc_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="movie",
            name="movie_count",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="movieuserlist",
            name="rented",
            field=models.BooleanField(default=False),
        ),
    ]
