# Generated by Django 5.0.4 on 2024-04-28 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_movie_disc_count_movie_genre_movie_movie_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="release",
        ),
        migrations.AddField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(0),
                    django.core.validators.MinValueValidator(9999),
                ],
            ),
        ),
        migrations.AddField(
            model_name="movieuserlist",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="movieuserlist",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(6),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
