# Generated by Django 5.0.4 on 2024-04-28 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_movie_release_movie_release_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(0),
                    django.core.validators.MinValueValidator(9999),
                ]
            ),
        ),
    ]
