# Generated by Django 5.0.4 on 2024-04-29 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_movie_release_year_alter_movieuserlist_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="movieuserlist",
            unique_together={("user", "movie")},
        ),
    ]
