# Generated by Django 5.0.4 on 2024-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_usersettings_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="show_view_details",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_view_title",
            field=models.BooleanField(default=True),
        ),
    ]
