# Generated by Django 5.0.4 on 2024-05-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_usersettings_show_view_details_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"verbose_name": "Movies", "verbose_name_plural": "Movies"},
        ),
        migrations.AlterModelOptions(
            name="movieuserlist",
            options={
                "verbose_name": "User Movie List",
                "verbose_name_plural": "User Movie List",
            },
        ),
        migrations.AlterModelOptions(
            name="usersettings",
            options={
                "verbose_name": "User Settings",
                "verbose_name_plural": "User Settings",
            },
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_view_new_icon",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_view_rented_icon",
            field=models.BooleanField(default=True),
        ),
    ]
