# Generated by Django 5.0.4 on 2024-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_alter_movie_options_alter_movieuserlist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="show_view_button_details",
            field=models.BooleanField(default=True),
        ),
    ]
