# Generated by Django 5.0.4 on 2024-05-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_usersettings_show_view_button_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="picture_available",
            field=models.BooleanField(default=False),
        ),
    ]
