# Generated by Django 5.0.4 on 2024-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_movie_picture_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="show_view_new_icon",
            new_name="show_view_icon_new",
        ),
        migrations.RenameField(
            model_name="usersettings",
            old_name="show_view_rented_icon",
            new_name="show_view_icon_rented",
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_view_count_discs",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="show_view_count_movies",
            field=models.BooleanField(default=True),
        ),
    ]
