# Generated by Django 5.0.4 on 2024-05-03 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0023_rename_show_view_new_icon_usersettings_show_view_icon_new_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersettings",
            old_name="show_view_count_discs",
            new_name="show_view_count_disc",
        ),
        migrations.RenameField(
            model_name="usersettings",
            old_name="show_view_count_movies",
            new_name="show_view_count_movie",
        ),
    ]
