# Generated by Django 5.0.4 on 2024-05-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0024_rename_show_view_count_discs_usersettings_show_view_count_disc_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="movieuserlist",
            name="viewed",
            field=models.BooleanField(default=False),
        ),
    ]
