# Generated by Django 5.0.4 on 2024-05-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_movieuserlist_viewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
