# Generated by Django 5.0.4 on 2024-05-06 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_movie_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="days_for_new",
            field=models.IntegerField(
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(730),
                ],
            ),
        ),
    ]
