# Generated by Django 5.0.4 on 2024-05-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_usersettings_days_for_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="movieuserlist",
            name="date_modified",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="movieuserlist",
            name="date_added",
            field=models.DateField(null=True),
        ),
    ]
