# Generated by Django 5.0.4 on 2024-05-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_alter_movieuserlist_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="date_modified",
            field=models.DateField(default="2024-01-01"),
        ),
    ]
