# Generated by Django 5.0.4 on 2024-05-21 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_alter_movieuserlist_date_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movieuserlist",
            name="date_modified",
        ),
    ]
