# Generated by Django 5.0.4 on 2024-05-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0032_remove_movieuserlist_date_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="date_added",
            field=models.DateField(),
        ),
    ]
