# Generated by Django 5.0.4 on 2024-05-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0033_alter_movieuserlist_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="date_added",
            field=models.DateField(editable=False),
        ),
    ]
