# Generated by Django 5.0.4 on 2024-05-21 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0034_alter_movieuserlist_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movieuserlist",
            name="date_added",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
