# Generated by Django 5.0.7 on 2024-08-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_alter_movieuserlist_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='episodes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='seasons_count',
            field=models.IntegerField(default=0),
        ),
    ]
