# Generated by Django 5.0.4 on 2024-08-09 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_movie_episodes_count_movie_seasons_count"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="episodes_count",
            new_name="episode_count",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="seasons_count",
            new_name="season_count",
        ),
    ]
