# Generated by Django 5.0.7 on 2024-08-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_movie_is_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='view_is_public',
            field=models.BooleanField(default=False),
        ),
    ]
