# Generated by Django 5.0.7 on 2024-10-09 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_usersettings_view_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='fsk_nbr',
            field=models.IntegerField(blank=True, default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
