# Generated by Django 5.0.7 on 2024-10-09 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_movie_fsk_nbr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fsk_nbr',
            field=models.IntegerField(blank=True, default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
