# Generated by Django 5.0.7 on 2024-10-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_movie_fsk_nbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='needs_parsing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='picture_url_original',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
