# Generated by Django 5.0.7 on 2024-10-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture_processed',
            field=models.BooleanField(default=False),
        ),
    ]
