# Generated by Django 5.0.7 on 2024-10-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_movie_picture_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture_url_original_hd',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
