# Generated by Django 5.0.7 on 2024-10-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_movie_picture_url_original_hd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
