# Generated by Django 5.1.5 on 2025-01-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_remove_todolist_user_delete_item_delete_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
