# Generated by Django 5.1.5 on 2025-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_alter_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_bluray_uhd',
            field=models.BooleanField(default=False),
        ),
    ]
