# Generated by Django 5.1.7 on 2025-03-27 22:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_movie_is_bluray_uhd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='days_for_new',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(730)], verbose_name='Days since adding a movie to show the new sign'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='price_unit',
            field=models.CharField(blank=True, default='€', max_length=3, verbose_name='Price Unit'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_button_details',
            field=models.BooleanField(default=True, verbose_name='Show the details button'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_count_disc',
            field=models.BooleanField(default=True, verbose_name='Show the number of disks'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_count_movie',
            field=models.BooleanField(default=True, verbose_name='Show the number of movies'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_details',
            field=models.BooleanField(default=True, verbose_name='Show Movie details'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_icon_new',
            field=models.BooleanField(default=True, verbose_name='Show the new sign'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_icon_rented',
            field=models.BooleanField(default=True, verbose_name='Show the rented sign'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_title',
            field=models.BooleanField(default=True, verbose_name='Show Movie title'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='view_is_public',
            field=models.BooleanField(default=False, verbose_name='The library can be viewed publicly'),
        ),
    ]
