# Generated by Django 5.1.7 on 2025-07-21 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='show_view_button_share',
            field=models.BooleanField(default=True, verbose_name='Show the share button'),
        ),
    ]
