# Generated by Django 5.1.7 on 2025-07-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_usersettings_show_view_button_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_count_disc',
            field=models.BooleanField(default=True, verbose_name='- Show the number of disks'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_count_movie',
            field=models.BooleanField(default=True, verbose_name='- Show the number of movies'),
        ),
    ]
