# Generated by Django 5.1.7 on 2025-10-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_movie_genre_alter_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='last_export',
            field=models.DateField(blank=True, null=True, verbose_name='Last time an export was executed'),
        ),
    ]
