# Generated by Django 5.1.7 on 2025-10-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_usersettings_last_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='last_export',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last time an export was executed'),
        ),
    ]
