# Generated by Django 5.2 on 2026-03-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_usersettings_last_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuserlist',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
