# Generated by Django 5.2 on 2026-03-25 19:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_movieuserlist_archived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='asin',
            field=models.CharField(max_length=16, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='disc_count',
            field=models.IntegerField(default=1, verbose_name='Disc Count'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ean',
            field=models.CharField(max_length=16, verbose_name='EAN'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='episode_count',
            field=models.IntegerField(default=0, verbose_name='Episode Count'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.CharField(max_length=16, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fsk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='FSK'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='fsk_nbr',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)], verbose_name='FSK NBR'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IMDb ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_bluray_uhd',
            field=models.BooleanField(default=False, verbose_name='Is Blu-ray UHD'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_series',
            field=models.BooleanField(default=False, verbose_name='Is Series'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_count',
            field=models.IntegerField(default=1, verbose_name='Movie Count'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='needs_parsing',
            field=models.BooleanField(default=True, verbose_name='Needs Parsing'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_available',
            field=models.BooleanField(default=False, verbose_name='Picture Available'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_processed',
            field=models.BooleanField(default=False, verbose_name='Picture Processed'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_url_original',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Picture URL Original'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture_url_original_hd',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Picture URL Original HD'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='regisseur',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Regisseur'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Release Year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.IntegerField(blank=True, null=True, verbose_name='Runtime'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='season_count',
            field=models.IntegerField(default=0, verbose_name='Season Count'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Studio'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_clean',
            field=models.CharField(max_length=128, verbose_name='Clean Title'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Activated'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Movie'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='rented',
            field=models.BooleanField(default=False, verbose_name='Rented'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='rented_to',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rented to'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movieuserlist', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Viewed'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_count_disc',
            field=models.BooleanField(default=True, verbose_name='Show the number of disks'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_count_movie',
            field=models.BooleanField(default=True, verbose_name='Show the number of movies'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
