# Generated by Django 5.2 on 2026-03-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_movie_actor_alter_movie_asin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_clean',
            field=models.CharField(max_length=128, verbose_name='Title Clean'),
        ),
    ]
