# Generated by Django 5.2 on 2026-04-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_alter_movie_title_clean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieuserlist',
            name='rented_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rented to'),
        ),
    ]
