# Generated by Django 5.2 on 2026-04-16 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_alter_movieuserlist_rented_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuserlist',
            name='url_custom',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Custom URL'),
        ),
        migrations.AddField(
            model_name='movieuserlist',
            name='url_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Custom URL Name'),
        ),
    ]
