# Generated by Django 5.2 on 2026-04-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_usercabinet_movieuserlist_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercabinet',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Cabinet Name'),
        ),
    ]
