# Generated by Django 5.2 on 2026-04-18 20:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_alter_usercabinet_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercabinet',
            unique_together={('user', 'name')},
        ),
    ]
