# Generated by Django 5.2 on 2026-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_alter_usercabinet_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='show_view_button_details',
            field=models.BooleanField(default=False, verbose_name='Show the details button'),
        ),
    ]
