# Generated by Django 5.2 on 2026-05-23 19:52

from django.db import migrations


def create_moderator_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Moderator-Movie")


def revert_moderator_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="Moderator-Movie").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0067_alter_usersettings_show_view_button_details"),
    ]

    operations = [
        migrations.RunPython(create_moderator_group, revert_moderator_group),
    ]
