# Generated by Django 5.2 on 2026-05-27 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0068_auto_20260523_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateField(default=django.utils.timezone.now, verbose_name='View Date')),
                ('watched_with', models.CharField(blank=True, max_length=255, null=True, verbose_name='Watched with')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('movie_user_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='main.movieuserlist', verbose_name='User Movie List')),
            ],
            options={
                'verbose_name': 'Movie View Log',
                'verbose_name_plural': 'Movie View Logs',
                'ordering': ['-view_date'],
            },
        ),
    ]
