# Generated by Django 5.2 on 2026-06-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_movieviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='force_picture_disable',
            field=models.BooleanField(default=False, verbose_name='Deactivate Picture'),
        ),
    ]
