# Generated by Django 5.2 on 2026-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_movie_force_picture_disable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='force_picture_disable',
            field=models.BooleanField(default=False, verbose_name='Force Deactivate Picture'),
        ),
    ]
