# Generated by Django 5.2 on 2026-06-05 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_alter_movie_force_picture_disable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_wrong', models.BooleanField(default=False, verbose_name='Picture Wrong')),
                ('content_wrong', models.BooleanField(default=False, verbose_name='Content Wrong')),
                ('wrong_ean_asin', models.BooleanField(default=False, verbose_name='Wrong EAN/ASIN')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment/Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='main.movie', verbose_name='Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_error_reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Movie Error Report',
                'verbose_name_plural': 'Movie Error Reports',
            },
        ),
    ]
