# Generated by Django 5.2 on 2026-06-05 09:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_movieerrorreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieerrorreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
    ]
