# Generated by Django 5.2 on 2026-06-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_alter_movieerrorreport_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieuserlist',
            name='rented_since',
            field=models.DateField(blank=True, null=True, verbose_name='Rented since'),
        ),
    ]
