# Generated by Django 5.2 on 2026-06-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_movieuserlist_rented_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_bluray_3d',
            field=models.BooleanField(default=False, verbose_name='Is Blu-ray 3D'),
        ),
    ]
