# Generated by Django 5.2 on 2026-06-10 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_movie_is_bluray_3d'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movieerrorreport',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Checked at'),
        ),
        migrations.AddField(
            model_name='movieerrorreport',
            name='checked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Checked by'),
        ),
        migrations.AddField(
            model_name='movieerrorreport',
            name='checked_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Checked Comment'),
        ),
    ]
