# Generated by Django 5.2 on 2026-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0076_movieerrorreport_checked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_clean',
            field=models.CharField(max_length=256, verbose_name='Title Clean'),
        ),
    ]
