# Generated by Django 5.2 on 2026-07-02 19:44

from django.db import migrations


def migrate_formats(apps, schema_editor):
    Format = apps.get_model("main", "Format")
    Movie = apps.get_model("main", "Movie")

    Format.objects.update_or_create(id=1, defaults={"name": "DVD"})
    Format.objects.update_or_create(id=2, defaults={"name": "Blu-Ray"})

    for movie in Movie.objects.all():
        if movie.format:
            format_obj, created = Format.objects.get_or_create(name=movie.format)
            movie.format_fk = format_obj
            movie.save()


def reverse_migrate(apps, schema_editor):
    Movie = apps.get_model("main", "Movie")
    for movie in Movie.objects.all():
        if movie.format_fk:
            movie.format = movie.format_fk.name
            movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0078_format_movie_format_fk"),
    ]

    operations = [
        migrations.RunPython(migrate_formats, reverse_migrate),
    ]
