# Generated by Django 5.2 on 2026-07-02 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0079_auto_20260702_2144"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="format",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="format_fk",
            new_name="format",
        ),
    ]
