# Generated by Django 5.2 on 2026-07-02 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_remove_movie_format_fk_alter_movie_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.format', verbose_name='Format'),
        ),
    ]
