# Generated by Django 5.2 on 2026-07-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_alter_movie_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.format', verbose_name='Format'),
            preserve_default=False,
        ),
    ]
