# Generated by Django 5.2 on 2026-07-05 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0082_alter_movie_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Activated'),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date added'),
        ),
        migrations.AddField(
            model_name='movie',
            name='date_updated',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date updated'),
        ),
        migrations.AddField(
            model_name='movie',
            name='flickrack_id',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Flickrack ID'),
        ),
    ]
