# Generated by Django 5.2 on 2026-07-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0083_movie_activated_movie_date_added_movie_date_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=128, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                to="main.language",
                verbose_name="Languages",
            ),
        ),
    ]
