# Generated by Django 5.2 on 2026-07-06 16:43

from django.db import migrations


def migrate_languages(apps, schema_editor):
    Language = apps.get_model("main", "Language")
    Movie = apps.get_model("main", "Movie")

    for movie in Movie.objects.all():
        if movie.language:
            raw_languages = movie.language.split(",")

            for raw_lang in raw_languages:
                lang_name = raw_lang.strip()

                if lang_name:
                    lang_obj, created = Language.objects.get_or_create(name=lang_name)

                    movie.languages.add(lang_obj)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0084_language_movie_languages"),
    ]

    operations = [
        migrations.RunPython(migrate_languages, None),
    ]
