# Generated by Django 5.2 on 2026-07-07 15:57

from django.db import migrations


def migrate_actors(apps, schema_editor):
    Actor = apps.get_model("main", "Actor")
    Movie = apps.get_model("main", "Movie")

    for movie in Movie.objects.all():
        if movie.actor:
            raw_actors = movie.actor.split(",")

            for raw_actor in raw_actors:
                actor_name = raw_actor.strip()

                if actor_name:
                    obj, created = Actor.objects.get_or_create(name=actor_name)

                    movie.actors.add(obj)


def migrate_studios(apps, schema_editor):
    Studio = apps.get_model("main", "Studio")
    Movie = apps.get_model("main", "Movie")

    for movie in Movie.objects.all():
        if movie.studio:
            raw_studios = movie.studio.split(",")

            for raw_studio in raw_studios:
                studio_name = raw_studio.strip()

                if studio_name:
                    obj, created = Studio.objects.get_or_create(name=studio_name)

                    movie.studios.add(obj)


def migrate_directors(apps, schema_editor):
    Director = apps.get_model("main", "Director")
    Movie = apps.get_model("main", "Movie")

    for movie in Movie.objects.all():
        if movie.regisseur:
            raw_directors = movie.regisseur.split(",")

            for raw_director in raw_directors:
                director_name = raw_director.strip()

                if director_name:
                    obj, created = Director.objects.get_or_create(name=director_name)

                    movie.directors.add(obj)


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0086_actor_director_studio_movie_actors_movie_directors_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_actors, None),
        migrations.RunPython(migrate_studios, None),
        migrations.RunPython(migrate_directors, None),
    ]
