# Generated by Django 5.2 on 2026-07-15 05:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20260707_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Name')),
                ('value', models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Content Rating',
                'verbose_name_plural': 'Content Ratings',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='content_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contentrating'),
        ),
    ]
