# Generated by Django 5.2 on 2026-07-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0090_alter_contentrating_name_alter_director_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
    ]
