# Generated by Django 5.2 on 2026-08-07 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_alter_movie_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieviewlog',
            name='episode',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Episode'),
        ),
        migrations.AddField(
            model_name='movieviewlog',
            name='season',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Season'),
        ),
    ]
