# Generated by Django 5.2 on 2026-08-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_movieviewlog_episode_movieviewlog_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='force_parsing',
            field=models.BooleanField(default=False, verbose_name='Force Parsing'),
        ),
    ]
