# Generated by Django 5.2 on 2026-08-31 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0093_movie_force_parsing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='content_rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.contentrating', verbose_name='Content Rating'),
        ),
        migrations.AlterField(
            model_name='movieuserlist',
            name='cabinet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usercabinet', verbose_name='Cabinet'),
        ),
    ]
