# Generated by Django 5.2 on 2026-08-31 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_alter_movie_content_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='actor',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fsk',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='fsk_nbr',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='regisseur',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='studio',
        ),
    ]
