# Generated by Django 6.1.1 on 2026-09-07 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0095_remove_movie_actor_remove_movie_fsk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieviewlog',
            name='view_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='View Date'),
        ),
    ]
