# Generated by Django 6.1.1 on 2026-09-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_alter_movieviewlog_view_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='asin',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, verbose_name='ASIN'),
        ),
    ]
