# Generated by Django 6.1.1 on 2026-10-05 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_alter_movie_asin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movieuserlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='movieuserlist',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Inventory Code'),
        ),
        migrations.AddConstraint(
            model_name='movieuserlist',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie'),
        ),
        migrations.AddConstraint(
            model_name='movieuserlist',
            constraint=models.UniqueConstraint(fields=('user', 'inventory_code'), name='unique_user_inventory_code'),
        ),
    ]
