# Generated by Django 6.1.1 on 2026-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_alter_movieuserlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='default_sort',
            field=models.CharField(choices=[('title_asc', 'Title A-Z'), ('title_desc', 'Title Z-A'), ('rating_asc', 'Rating ascending'), ('rating_desc', 'Rating descending'), ('date_asc', 'Date added ascending'), ('date_desc', 'Date added descending'), ('runtime_asc', 'Runtime ascending'), ('runtime_desc', 'Runtime descending'), ('inventory_code_asc', 'Inventory code ascending'), ('inventory_code_desc', 'Inventory code descending')], default='title_asc', max_length=30, verbose_name='Default sorting'),
        ),
    ]
