# Generated by Django 6.1.1 on 2026-10-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_alter_usersettings_default_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='default_sort',
            field=models.CharField(choices=[('title_asc', 'Title (A-Z)'), ('title_desc', 'Title (Z-A)'), ('runtime_asc', 'Runtime (Shortest)'), ('runtime_desc', 'Runtime (Longest)'), ('date_asc', 'Date (Oldest)'), ('date_desc', 'Date (Newest)'), ('inventory_code_asc', 'Inventory Code (A-Z)'), ('inventory_code_desc', 'Inventory Code (Z-A)'), ('rating_asc', 'Rating (Lowest)'), ('rating_desc', 'Rating (Highest)')], default='title_asc', max_length=30, verbose_name='Default sorting'),
        ),
    ]
