# Generated by Django 5.2 on 2026-05-11 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedAddMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(max_length=16, verbose_name='EAN')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date added')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
            ],
            options={
                'verbose_name': 'Failed Movie Import',
                'verbose_name_plural': 'Failed Movie Imports',
            },
        ),
    ]
