# Generated by Django 5.2 on 2026-06-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenthandler', '0001_initial'),
        ('main', '0069_movieviewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedaddmovie',
            name='is_movie_update',
            field=models.BooleanField(default=False, verbose_name='Is Existing Movie'),
        ),
        migrations.AddField(
            model_name='failedaddmovie',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.movie', verbose_name='Movie'),
        ),
    ]
